### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by bloha** [rajce-client/data-structures#1]
# v1 Roadmap
- [ ] Linked List
- [ ] Queue (based on Linked List)
- [ ] Pairing Heap
- [ ] Priority Queue (based on Pairing Heap)
- [ ] Priority Queue (optimal for statically defined priorities)
